name: Release
on:
  workflow_dispatch:
    inputs: {}

# Serialize workflow runs
# concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  RUST_VERSION: 1.71

jobs:
  build-and-sign:
    name: build and sign release assets
    runs-on: ${{ matrix.config.os }}
    # permissions:
    #   # cosign uses the GitHub OIDC token
    #   id-token: write
    #   # needed to upload artifacts to a GH release
    #   contents: write
    strategy:
      matrix:
        config:
          - {
              os: "ubuntu-20.04",
              arch: "amd64",
              extension: "",
              # Ubuntu 22.04 no longer ships libssl1.1, so we statically
              # link it here to preserve release binary compatibility.
              extraArgs: "--features openssl/vendored",
              target: "",
              targetDir: "target/release",
            }
          - {
              os: "ubuntu-20.04",
              arch: "aarch64",
              extension: "",
              extraArgs: "--features openssl/vendored --target aarch64-unknown-linux-gnu",
              target: "aarch64-unknown-linux-gnu",
              targetDir: "target/aarch64-unknown-linux-gnu/release",
            }
          - {
              os: "macos-latest",
              arch: "amd64",
              extension: "",
              extraArgs: "",
              target: "",
              targetDir: "target/release",
            }
          - {
              os: "macos-latest",
              arch: "aarch64",
              extension: "",
              extraArgs: "--target aarch64-apple-darwin",
              target: "aarch64-apple-darwin",
              targetDir: "target/aarch64-apple-darwin/release/",
            }
          - {
              os: "windows-latest",
              arch: "amd64",
              extension: ".exe",
              extraArgs: "",
              target: "",
              targetDir: "target/release",
            }
    steps:
      - uses: actions/checkout@v3

      - name: Copy Binary to S3 - ${{ env.RELEASE_VERSION }}
        #if: ${{ (runner.os == 'Linux') && (matrix.config.arch == 'amd64')  && (github.repository_owner == 'rajatjindal') }}
        if: runner.os == 'linux' && matrix.config.arch == 'amd64' && ${{ github.repository_owner == 'rajatjindal' }}
        run: |
          echo "called ${{ runner.os }} - ${{ matrix.config.arch }} ${{ github.repository_owner }}"
